### PR TITLE
Changed 'My reports' bite tab icon

### PR DESCRIPTION
**Pull request by epou**

### CODE REVIEW

**Review by DigitalSeneca — COMMENTED** [review]
The icon itself looks good :)
but it seems smaller compared to the mosquito icon on its left
image

**Comment by epou** [comment]
Could you try again with this? (removed transparent margin)

bite icon

**Comment by DigitalSeneca** [comment]
> Could you try again with this? (removed transparent margin)
> 
> bite icon

still looks small, can you try without the transparent margin but still keeping it a square? I'm thinking the problem could be the new image being a rectangle

**Comment by epou** [comment]
Well.... in that case maybe it's worth trying with a different image. How about this?

bite2

**Comment by DigitalSeneca** [comment]
This one looks much better! Do you want me to push a commit with it or are you going to do it?

image

**Comment by epou** [comment]
Could you commit it for me? I'm not at the office right now

**Comment by DigitalSeneca** [comment]
done!

**Pull request merged**
