### PR TITLE
Remove version_control.dart dribba

### LINKED ISSUE #146: Remove version_control.dart
We are no longer working with the company that provide the API endpoint used to check the version + this is prone to errors.

### PR DESCRIPTION
**Pull request by DigitalSeneca**
fixes #146 

To me it seems that there are no side affects. I'm not sure if I should test something specific

### CODE REVIEW

**Review by epou — COMMENTED** [review]
Looks good to me, shouldn't be any side effect... Maybe it would be a good idea to rename main_vc.dart to main.dart?

**Comment by DigitalSeneca** [comment]
> Looks good to me, shouldn't be any side effect... Maybe it would be a good idea to rename main_vc.dart to main.dart?

Then we have 2 main.dart files. Maybe it's more appropriate to name it something related to the drawer/header, since that's the most contents of this file

**Comment by epou** [comment]
Yes, just choose a name that makes sense and makes you feel comfortable. Feel free

**Comment by DigitalSeneca** [comment]
How does `drawer_and_header.dart` sound?

**Comment by epou** [comment]
Go for it! Sounds good to me :+1:

**Pull request merged**
